# Generated by Django 3.2.7 on 2021-10-06 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_product', '0002_rename_description_product_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
