# Generated by Django 3.2.7 on 2021-10-06 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_product', '0004_auto_20211006_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
